#!/usr/bin/env python3

# Import required Python code.
import roslib
NODE_NAME = 'ck_utilities_py_node'
roslib.load_manifest(NODE_NAME)
import rospy
import tf2_ros
import ck_utilities_py_node.main as main
if __name__ == '__main__':
    main.ros_main(NODE_NAME)